grails-app/controllers/co/xtrava/UserController.groovy
package co.xtrava

import co.xtrava.auth.Role
import co.xtrava.auth.User
import co.xtrava.auth.UserRole
import grails.plugin.springsecurity.SpringSecurityUtils
import org.springframework.dao.DataIntegrityViolationException

/**
 * UserController
 * A controller class handles incoming web requests and performs actions such as redirects, rendering views and so on.
 */
class UserController {
    def baseSearchService
    def userCache
    def springSecurityService

    static allowedMethods = [save: "POST", update: "POST", delete: "POST"]

    def index() {
        redirect(action: "list")
    }

    def profile() {
        [user: springSecurityService.currentUser as User]
    }

    def editProfile() {
        [user: springSecurityService.currentUser as User]
    }


    def updateProfile() {
        def user = springSecurityService.currentUser as User
        bindData(user, params, ["password"])

        if (params.'password') {
            if (params.'password' != params.'confirmPassword') {
                flash.message = g.message(code: 'password.wrongConfirm')
                render(view: "editProfile", model: [user: user])
                return
            }
            user.password = params.'password'
        }


        if (!user.save(flush: true)) {
            render(view: "editProfile", model: [user: user])
            return
        }

        flash.message = message(code: 'default.updated.message', args: [message(code: 'user.label'), user.id])
        render(view: "profile", model: [user: user])
    }

    def list() {
        params.max = Math.min(params.max ? params.int('max') : 10, 100)
        def searchParam = params.keyword

        Closure searchRestriction = { builder ->
            if (searchParam) {
                builder.or {

                    builder.ilike("email", "%${searchParam}%")

                    builder.ilike("password", "%${searchParam}%")

                }
            }
        }

        def domains = baseSearchService.retrieveListForObject(User, params, searchRestriction)
        def domainsTotal = baseSearchService.getCountForObject(User, params, searchRestriction)
        [userInstanceList: domains, userInstanceTotal: domainsTotal]
    }

    def create() {
        [userInstance: new User(params)]
    }

    def save() {
        User user = new User()
        bindData(user, params, ['password'])
        if (params.password && params.password == params.confirmPassword) {
            user.password = params.password
        } else {
            flash.error = message(code: 'password.not.match')
            redirect action: 'create', params: params
        }
        if (!user.save(flush: true)) {
            render(view: "create", model: [userInstance: user])
            return
        }
        addRoles(user)
        flash.message = message(code: 'default.created.message', args: [message(code: 'user.label', default: 'User'), user.id])
        redirect(action: "show", id: user.id)
    }

    def show() {
        def userInstance = User.get(params.id)
        if (!userInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'user.label', default: 'User'), params.id])
            redirect(action: "list")
            return
        }

        [userInstance: userInstance]
    }

    def edit() {
        def userInstance = User.get(params.id)
        if (!userInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'user.label', default: 'User'), params.id])
            redirect(action: "list")
            return
        }

        buildUserModel(userInstance)
    }

    def update(Long id) {
        User user = User.get(id)

        if (!user) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'user.label', default: 'User'), params.id])
            redirect(action: "list")
            return
        }

        if (params.version) {
            def version = params.version.toLong()
            if (user.version > version) {
                user.errors.rejectValue("version", "default.optimistic.locking.failure",
                        [message(code: 'user.label')] as Object[],
                        "Another user has updated this User while you were editing")
                render(view: "edit", model: [userInstance: user])
                return
            }
        }
        bindData(user, params, ['password'])
        if (params.password && params.password == params.confirmPassword) {
            user.password = params.password
        } else if (params.password && params.confirmPassword) {
            flash.error = message(code: 'password.not.match')
            redirect action: 'edit', id: id, params: params
        }
        UserRole.removeAll(user)
        addRoles(user)
        userCache.removeUserFromCache(user.email)
        if (!user.save(flush: true)) {
            render(view: "edit", model: buildUserModel(user))
            return
        }

        flash.message = message(code: 'default.updated.message', args: [message(code: 'user.label', default: 'User'), user.id])
        redirect(action: "show", id: user.id)
    }

    def delete() {
        def userInstance = User.get(params.id)
        if (!userInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'user.label', default: 'User'), params.id])
            redirect(action: "list")
            return
        }

        try {
            userInstance.delete(flush: true)
            flash.message = message(code: 'default.deleted.message', args: [message(code: 'user.label', default: 'User'), params.id])
            redirect(action: "list")
        }
        catch (DataIntegrityViolationException e) {
            flash.message = message(code: 'default.not.deleted.message', args: [message(code: 'user.label', default: 'User'), params.id])
            redirect(action: "show", id: params.id)
        }
    }

    private void addRoles(User user) {
        for (String key in params.keySet()) {
            if (key.contains('ROLE') && 'on' == params.get(key)) {
                UserRole.create(user, Role.findByAuthority(key), true)
            }
        }
    }

    private Map buildUserModel(User user) {
        List<Role> roles = Role.list().sort { it.authority }
        def granted = [:]
        def notGranted = [:]
        if (user.id) {
            Set userRoleNames = user.authorities.collect { it.authority }

            if (SpringSecurityUtils.ifAllGranted("ROLE_ADMIN")) {
                for (role in roles) {
                    String authority = role.authority
                    if (userRoleNames.contains(authority)) {
                        granted[(role)] = userRoleNames.contains(authority)
                    } else {
                        notGranted[(role)] = userRoleNames.contains(authority)
                    }
                }
            }
        } else {
            for (role in roles) {
                notGranted[(role)] = false
            }
        }

        return [userInstance: user, roleMap: granted + notGranted]
    }
}

grails-app/views/user/_form.gsp
<%@ page import="co.xtrava.auth.User" %>



<f:field property="email" input-class="form-control"/>

<div class="form-group">
  <label for="password" class="col-sm-2 control-label no-padding-right">
    <span class="text-danger">*</span>Password
  </label>

  <div class="col-md-8 col-sm-8 col-lg-8">
    <input type="password" class="form-control" name="password" id="password">
  </div>
</div>

<div class="form-group">
  <label for="confirmPassword" class="col-sm-2 control-label no-padding-right">
    <span class="text-danger">*</span>Confirm password
  </label>

  <div class="col-md-8 col-sm-8 col-lg-8">
    <input type="password" class="form-control" name="confirmPassword" id="confirmPassword">
  </div>
</div>

<f:field property="accountExpired" input-class="form-control"/>

<f:field property="accountLocked" input-class="form-control"/>

<f:field property="enabled" input-class="form-control"/>

<f:field property="passwordExpired" input-class="form-control"/>

grails-app/views/user/_menu.gsp
<ul class="nav nav-tabs tab-padding tab-space-3 tab-blue" id="myTab4">
  <li class="${active == 'profile' ? 'active' : ''}">
    <g:link controller="user" action="profile">
      <g:message code="user.profile.overview"/>
    </g:link>
  </li>
  <li class="${active != 'profile' ? 'active' : ''}">
    <g:link controller="user" action="editProfile">
      <g:message code="user.profile.edit"/>
    </g:link>
  </li>
</ul>

grails-app/views/user/create.gsp
<%@ page import="co.xtrava.auth.Role; co.xtrava.auth.User" %>
<!doctype html>
<html>

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="layout" content="dashboard"/>
  <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}"/>
  <title><g:message code="default.create.label" args="[entityName]"/></title>
</head>

<body>
<div class="page-header">
  <g:link action="list" class="btn btn-purple">
    <i class="fa fa-th-list"></i>
    <g:message code="default.list.label" args="[entityName]"/>
  </g:link>
</div>

<div id="create-user" class="page-content">
  <g:hasErrors bean="${userInstance}">
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">
        <i class="fa fa-remove"></i>
      </button>
      <g:renderErrors bean="${userInstance}" as="list"/>
    </div>
  </g:hasErrors>

  <g:form action="save" class="form-horizontal" >

  <f:with bean="${userInstance}">
    <g:render template="form"/>
    <h3 class="sub_header"><g:message code="user.roles"/></h3>
    <hr/>

    <div class="form-group">
      <g:each in="${co.xtrava.auth.Role.findAll()}" var="role">

        <div class="col-md-8 col-sm-8 col-lg-8 sub_header">
          <label>
            <g:checkBox name="${role.authority}"/>
            ${role.authority}
          </label>
        </div>
      </g:each>
    </div>
  </f:with>

  <g:render template="/_menu/bottomActionButtons"/>
  </g:form>

</div>

</body>

</html>

grails-app/views/user/edit.gsp
<!doctype html>
<html>

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="layout" content="dashboard"/>
  <g:set var="entityName" value="${message(code: 'user.label')}"/>
  <title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>

<div class="page-header">
  <g:link action="list" class="btn btn-purple">
    <i class="fa fa-th-list"></i>
    <g:message code="default.list.label" args="[entityName]"/>
  </g:link>
</div>

<div id="edit-user" class="page-content">
  <g:hasErrors bean="${userInstance}">
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">
        <i class="fa fa-remove"></i>
      </button>
      <g:renderErrors bean="${userInstance}" as="list"/>
    </div>
  </g:hasErrors>

  <g:form method="post" class="form-horizontal">

    <g:hiddenField name="id" value="${userInstance?.id}"/>
    <g:hiddenField name="version" value="${userInstance?.version}"/>

    <f:with bean="${userInstance}">
      <div class="edit-boundary">
        <g:render template="form"/>
        <h3 class="sub_header"><g:message code="user.roles"/></h3>
        <hr/>

        <div class="form-group">
          <g:each var="entry" in="${roleMap}">

            <div class="col-md-8 col-sm-8 col-lg-8 sub_header">
              <label>
                <g:checkBox name="${entry.key.authority}" value="${entry.value}"/>
                ${entry.key.authority.encodeAsHTML()}
              </label>
            </div>
          </g:each>
        </div>
      </div>
    </f:with>
    <g:render template="/_menu/bottomActionButtons"/>
  </g:form>
</div>

</body>

</html>

grails-app/views/user/editProfile.gsp
<!doctype html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="layout" content="dashboard"/>
  <title><g:message code="user.profile.edit"/></title>
</head>

<body>
<div class="row">
  <div class="col-sm-12">
    <div class="tabbable">
      <g:render template="menu"/>

      <div class="tab-content">
        <g:render template="/_menu/infomessages"/>
        <div id="panel_overview" class="tab-pane active">
          <g:form controller="user" action="updateProfile" role="form" id="form">
            <div class="row">
              <div class="col-md-12">
                <h3>Account Info</h3>
                <hr>
              </div>

              <div class="col-md-6">

                <div class="form-group">
                  <label class="control-label">
                    <g:message code="user.email.label"/>
                  </label>
                  <input type="email" value="${user?.email}" class="form-control" id="email" name="email">
                </div>

                <div class="form-group">
                  <label class="control-label">
                    <g:message code="user.password.label"/>
                  </label>
                  <input type="password" placeholder="Password" class="form-control" name="password" id="password">
                </div>

                <div class="form-group">
                  <label class="control-label">
                    <g:message code="user.confirmPassword.label"/>
                  </label>
                  <input type="password" placeholder="Confirm Password" class="form-control" id="confirmPassword"
                         name="confirmPassword">
                </div>
              </div>
            </div>


            <div class="row">

              <div class="col-md-4">
                <button class="btn btn-teal btn-block" type="submit">
                  <g:message code="common.update"/> <i class="fa fa-arrow-circle-right"></i>
                </button>
              </div>
            </div>
          </g:form>
        </div>
      </div>
    </div>
  </div>
</div>

</body>
</html>

grails-app/views/user/index.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-user" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="createdBy" title="${message(code: 'user.createdBy.label', default: 'Created By')}" />
					
						<g:sortableColumn property="email" title="${message(code: 'user.email.label', default: 'Email')}" />
					
						<g:sortableColumn property="password" title="${message(code: 'user.password.label', default: 'Password')}" />
					
						<g:sortableColumn property="accountExpired" title="${message(code: 'user.accountExpired.label', default: 'Account Expired')}" />
					
						<g:sortableColumn property="accountLocked" title="${message(code: 'user.accountLocked.label', default: 'Account Locked')}" />
					
						<g:sortableColumn property="dateCreated" title="${message(code: 'user.dateCreated.label', default: 'Date Created')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${userInstanceList}" status="i" var="userInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${userInstance.id}">${fieldValue(bean: userInstance, field: "createdBy")}</g:link></td>
					
						<td>${fieldValue(bean: userInstance, field: "email")}</td>
					
						<td>${fieldValue(bean: userInstance, field: "password")}</td>
					
						<td><g:formatBoolean boolean="${userInstance.accountExpired}" /></td>
					
						<td><g:formatBoolean boolean="${userInstance.accountLocked}" /></td>
					
						<td><g:formatDate date="${userInstance.dateCreated}" /></td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${userInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/user/list.gsp
<!doctype html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="layout" content="dashboard"/>
  <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}"/>
  <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<div class="page-header">
  <g:link action="list" class="btn btn-purple">
    <i class="fa fa-th-list"></i>
    <g:message code="default.list.label" args="[entityName]"/>
  </g:link>
  <g:link action="create" class="btn btn-success">
    <i class="fa fa-plus"></i>
    <g:message code="default.new.label" args="[entityName]"/>
  </g:link>
</div>


<div id="list-user" class="page-content">
  <g:if test="${userInstanceTotal}">

    <table class="table table-bordered dataTable">
      <thead>
      <tr>
        
        <g:sortableColumn property="email"
                          title="${message(code: 'user.email.label', default: 'Email')}"/>

        <g:sortableColumn property="enabled"
                          title="${message(code: 'user.enabled.label')}"/>
        
        <g:sortableColumn property="dateCreated"
                          title="${message(code: 'user.dateCreated.label', default: 'Date Created')}"/>
        
      </tr>
      </thead>
      <tbody>
      <g:each in="${userInstanceList}" status="i" var="userInstance">
        <f:with bean="${userInstance}">

          <tr class="${(i % 2) == 0 ? 'odd' : 'even'}">
            
            <td>
              <g:link action="show" id="${userInstance.id}">
                <f:display property="email"/>
              </g:link>
            </td>
            
            <td><f:display property="enabled"/></td>

            <td><f:display property="dateCreated"/></td>
            
          </tr>
        </f:with>
      </g:each>
      </tbody>
    </table>

    <bs:paginate total="${userInstanceTotal}"/>
  </g:if>
  <g:else>
    <g:render template="/_search/noResult" model='[collection: "userInstance"]'/>
  </g:else>
</div>

</body>

</html>

grails-app/views/user/profile.gsp
<!doctype html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="layout" content="dashboard"/>
    <title><g:message code="user.show.label"/></title>
</head>

<body>

<div class="row">
    <div class="col-sm-12">
        <div class="tabbable">
            <g:render template="menu" model="[active: 'profile']"/>

            <div class="tab-content">
                <div id="panel_overview" class="tab-pane active">
                    <div class="row">
                        <div class="col-sm-5 col-md-4">
                            <div class="user-left">
                                <div class="center">
                                    <h4>${user}</h4>
                                    <hr>

                                    <p>
                                        <a class="btn btn-twitter btn-sm btn-squared">
                                            <i class="fa fa-twitter"></i>
                                        </a>
                                        <a class="btn btn-linkedin btn-sm btn-squared">
                                            <i class="fa fa-linkedin"></i>
                                        </a>
                                        <a class="btn btn-google-plus btn-sm btn-squared">
                                            <i class="fa fa-google-plus"></i>
                                        </a>
                                        <a class="btn btn-github btn-sm btn-squared">
                                            <i class="fa fa-github"></i>
                                        </a>
                                    </p>
                                    <hr>
                                </div>
                                <table class="table table-condensed table-hover">
                                    <thead>
                                    <tr>
                                        <th colspan="3"><g:message code="user.contactInformation"/></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td><g:message code="user.email.label"/></td>
                                        <td>
                                            <a href="mailto:${user.email}">
                                                <g:fieldValue bean="${user}" field="email"/>
                                            </a>
                                        </td>
                                        <td><a href="${createLink(action: 'editProfile')}"><i
                                                class="fa fa-pencil edit-user-info"></i></a>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>

                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
</body>

</html>

grails-app/views/user/show.gsp
<!doctype html>
<html>

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="layout" content="dashboard"/>
  <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}"/>
  <title><g:message code="default.show.label" args="[entityName]"/></title>
</head>

<body>

<div class="page-header">
  <g:link action="list" class="btn btn-purple">
    <i class="fa fa-th-list"></i>
    <g:message code="default.list.label" args="[entityName]"/>
  </g:link>
  <g:link action="edit" id="${userInstance?.id}" class="btn btn-primary">
    <i class="fa fa-pencil"></i>
    <g:message code="default.edit.label" args="[entityName]"/>
  </g:link>
  <g:render template="/_common/modals/deleteTextLink"/>
</div>

    <div id="show-user" class="page-content">
      <table class="table table-bordered">
        <tbody>
        
        <tr class="prop">
          <td valign="top" class="name"><g:message code="user.email.label"
                                                   default="Email"/></td>
          
          <td valign="top" class="value"><f:display bean="${userInstance}" property="email"/></td>
          
        </tr>

        <tr class="prop">
          <td valign="top" class="name"><g:message code="user.accountExpired.label"
                                                   default="Account Expired"/></td>
          
          <td valign="top" class="value"><f:display bean="${userInstance}" property="accountExpired"/></td>
          
        </tr>
        
        <tr class="prop">
          <td valign="top" class="name"><g:message code="user.accountLocked.label"
                                                   default="Account Locked"/></td>
          
          <td valign="top" class="value"><f:display bean="${userInstance}" property="accountLocked"/></td>
          
        </tr>
        
        <tr class="prop">
          <td valign="top" class="name"><g:message code="user.enabled.label"
                                                   default="Enabled"/></td>
          
          <td valign="top" class="value"><f:display bean="${userInstance}" property="enabled"/></td>
          
        </tr>
        
        <tr class="prop">
          <td valign="top" class="name"><g:message code="user.passwordExpired.label"
                                                   default="Password Expired"/></td>
          
          <td valign="top" class="value"><f:display bean="${userInstance}" property="passwordExpired"/></td>
          
        </tr>
        
        </tbody>
      </table>

    </div>
</body>

</html>