grails-app/controllers/co/xtrava/HomeController.groovy
package co.xtrava

import co.xtrava.auth.Role
import grails.plugin.springsecurity.SpringSecurityUtils

/**
 * @author: Dmitry Lesnikovich
 */
class HomeController {
    def springSecurityService

    def index() {
        if(springSecurityService.isLoggedIn()) {
            if (SpringSecurityUtils.ifAnyGranted(Role.AvailableRoles.ADMIN.value())) {
                redirect(controller: 'user', action: "list")
            } else {
                redirect controller: 'dataRest', action: 'tester'
            }
        } else {
            redirect controller: 'login', action: 'auth'
        }
    }
}

grails-app/views/_menu/_admin.gsp
<ul class="nav pull-right">
  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
      <i class="icon-wrench"></i>
      <g:message code="default.admin.label"/><b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
      <li class="">
        <a tabindex="-1" href="#"><b>Technical Admin</b></a>
      </li>
      <g:if env="development">
        <li class="">
          <a href="${createLink(uri: '/dbconsole')}">
            <i class="icon-dashboard"></i>
            <g:message code="default.dbconsole.label"/>
          </a>
        </li>
      </g:if>
      <li class="">
        <a href="${createLink(uri: '/systeminfo')}">
          <i class="icon-info-sign"></i>
          <g:message code="default.systeminfo.label"/>
        </a>
      </li>
      <li class="dropdown-submenu">
        <a tabindex="-1" href="#">
          <i class="icon-sitemap"></i>
          All Controller
        </a>
        <ul class="dropdown-menu">
          <li class="controller"><g:link controller="home">HomeController</g:link></li>
          <li class="divider"></li>
          <g:each var="c" in="${grailsApplication.controllerClasses.sort { it.logicalPropertyName }}">
            <g:if test="${c.logicalPropertyName != 'home'}">
              <li class="controller"><g:link
                  controller="${c.logicalPropertyName}">${c?.fullName?.substring(c?.fullName?.lastIndexOf('.') + 1)}</g:link></li>
            </g:if>
          </g:each>
        </ul>
      </li>
    </ul>
  </li>
</ul>

grails-app/views/_menu/_bottomActionButtons.gsp
<g:set var="entityName"
       value="${message(code: params.controller + '.label', default: params.controller?.substring(0, 1)?.toUpperCase() + params.controller.substring(1).toLowerCase())}"/>

<div class="clearfix form-actions space20">
  <div class="col-md-offset-3 col-md-9">
    <g:if test="${['edit', 'update', 'index'].contains(params.action)}">
      <g:render template="/_common/buttons/edit"/>

      <g:render template="/_common/buttons/reset"/>

      <g:render template="/_common/buttons/cancel"/>
    </g:if>
    <g:elseif test="${['create', 'save'].contains(params.action)}">
      <g:render template="/_common/buttons/create"/>

      <g:if test="${params.action == 'save'}">
        <g:render template="/_common/buttons/reset"/>
      </g:if>

      <g:render template="/_common/buttons/cancel"/>
    </g:elseif>
  </div>
</div>

grails-app/views/_menu/_breadcrumbs.gsp
<%@ page import="org.apache.commons.lang.WordUtils" %>
<ul class="breadcrumb">
  <li>
    <i class="fa fa-home"></i>
    <g:link controller="${params.controller}">${WordUtils.capitalize(params.controller)}</g:link>
  </li>

  <li class="active">${params.action instanceof String ? WordUtils.capitalize(params.action) : ''}</li>

  <g:if test="${params.id}">
    <li class="active">${params.id}</li>
  </g:if>
</ul><!-- .breadcrumb -->

grails-app/views/_menu/_errorInfoMessages.gsp
<div class="alert alert-danger">
  ${errorMessage}
  <button type="button" class="close" data-dismiss="alert">
    <i class="fa fa-times"></i>
  </button>
</div>

grails-app/views/_menu/_errors.gsp
<g:hasErrors bean="${bean}">
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert">
      <i class="fa fa-times"></i>
    </button>
    <g:renderErrors bean="${bean}" as="list"/>
  </div>
</g:hasErrors>

grails-app/views/_menu/_info.gsp
<ul class="nav pull-right">
  <li class="dropdown dropdown-btn">

    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
      <i class="icon-info-sign"></i>
      <g:message code="default.info.label"/> <b class="caret"></b>
    </a>

    <ul class="dropdown-menu">

      <%-- Note: Links to pages without controller are redirected in conf/UrlMappings.groovy --%>
      <li class="">
        <a href="${createLink(uri: '/about')}">
          <i class="icon-info-sign"></i>
          <g:message code="default.about.label"/>
        </a>
      </li>
      <li class="">
        <a href="http://wordpress.com/signup/">
          <i class="icon-align-justify"></i>
          <i><g:message code="default.blog.label"/></i>
        </a>
      </li>
      <li class="">
        <a href="${createLink(uri: '/contact')}">
          <i class="icon-envelope"></i>
          <g:message code="default.contact.label"/>
        </a>
      </li>

      <%--			<li class="divider"></li>--%>
      <%--			<li class=""><a href="${createLink(uri: '/imprint')}">Imprint</a></li>--%>
      <%--			<li class=""><a href="${createLink(uri: '/terms')}"><i>Terms of Use</i></a></li>--%>
    </ul>
  </li>
</ul>

grails-app/views/_menu/_infomessages.gsp
<g:if test="${(flash.message && !layout_noflashmessage) || customMessage}">
  <div class="alert alert-info">
    ${flash.message ?: customMessage}
    <button type="button" class="close" data-dismiss="alert">
      <i class="fa fa-times"></i>
    </button>
  </div>
</g:if>
<g:if test="${(flash.error && !layout_noflashmessage) || customMessage}">
  <div class="alert alert-danger">
    ${flash.error ?: customMessage}
    <button type="button" class="close" data-dismiss="alert">
      <i class="fa fa-times"></i>
    </button>
  </div>
</g:if>

grails-app/views/_menu/_language.gsp
<g:set var="lang"
       value="${session.'org.springframework.web.servlet.i18n.SessionLocaleResolver.LOCALE' ?: org.springframework.web.servlet.support.RequestContextUtils.getLocale(request).toString().substring(0, 2)}"/>
<g:set var="currentURL" value="${request.forwardURI}"/>

<ul class="nav secondary-nav language-dropdown pull-right">
  <li class="dropdown dropdown-btn js-language-dropdown">
    <a class="dropdown-toggle" role="button" data-toggle="dropdown" data-target="#" href="javascript:;">
      <img class=""
           src="${resource(plugin: 'kickstart-with-bootstrap', dir: 'images/flags', file: lang.toString() + '.png')}"/>
    </a>
    <ul class="dropdown-menu dropdown-menu-dark" role="menu">

      <!-- assuming that the default locale is English -->
      <li><a class="js-language-link" title="English" data-lang-code="en" href="${currentURL + '?lang=en'}">
        <img class="" src="${resource(plugin: 'kickstart-with-bootstrap', dir: 'images/flags', file: 'en.png')}"/>
        <g:message code="language.en" default="en"/> ${currentlURL}
      </a></li>

      <li class="divider"></li>

    <!-- get list of all locales available due to an existing property-file in /grails-app/i18n (set once in Bootstrap.groovy) -->
      <g:set var="allLocales" value="${grailsApplication.config.grails.i18n.locales}"/>
      <g:each status="i" var="locale" in="${allLocales}">
        <li><a class="js-language-link" title="${message(code: 'language.' + locale, default: locale)}"
               data-lang-code="${locale}" href="${currentURL + '?lang=' + locale}">
          <img class=""
               src="${resource(plugin: 'kickstart-with-bootstrap', dir: 'images/flags', file: locale + '.png')}"/>
          <g:message code="language.${locale}" default="${locale}"/>
        </a></li>
      </g:each>

    </ul>
  </li>
</ul>

grails-app/views/_menu/_menubar.gsp
<div class="well sidebar-nav">
  <ul class="nav nav-pills nav-stacked" data-role="listview" data-split-icon="gear" data-filter="true">

    <g:each status="i" var="c" in="${grailsApplication.controllerClasses.sort { it.logicalPropertyName }}">
      <li class="controller${params.controller == c.logicalPropertyName ? " active" : ""}">
        <g:link controller="${c.logicalPropertyName}" action="index">
          <g:message code="${c.logicalPropertyName}.label" default="${c.logicalPropertyName.capitalize()}"/>
        </g:link>
      </li>
    </g:each>

  </ul>
</div>

grails-app/views/_menu/_navbar.gsp
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle" type="button">
        <span class="clip-list-2"></span>
      </button>
      <g:link uri="/">
        <asset:image src="dashboard/logo.png" class="logo"/>
      </g:link>
    </div>

    <div class="navbar-tools">
      <!-- start: TOP NAVIGATION MENU -->
      <ul class="nav navbar-right">

        <li class="dropdown current-user">
          <a data-toggle="dropdown" class="dropdown-toggle" href="#">

            <span class="user-info">
              <sec:ifNotLoggedIn>Please, sign in</sec:ifNotLoggedIn> <sec:loggedInUserInfo field="username"/>
              <i class="fa fa-chevron-down"></i>
            </span>
          </a>
          <ul class="dropdown-menu">
            <sec:ifLoggedIn>
              <li>
                <g:link controller="user" action="profile">
                  <i class="fa fa-user"></i>
                  <g:message code="person.profile"/>
                </g:link>
              </li>
              <li class="divider"></li>
            </sec:ifLoggedIn>
            <sec:ifNotLoggedIn>
              <li>
                <g:link controller="login" action="auth">
                  <i class="fa fa-key"></i>
                  <g:message code="login"/>
                </g:link>
              </li>
            </sec:ifNotLoggedIn>
            <sec:ifLoggedIn>
              <li>
                <g:link controller="logout">
                  <i class="fa fa-power-off"></i>
                  <g:message code="logout"/>
                </g:link>
              </li>
            </sec:ifLoggedIn>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</div>

grails-app/views/_menu/_submenubar.gsp
<%@ page import="co.xtrava.auth.Role" %>
<!--
This menu is used to show function that can be triggered on the content (an object or list of objects).
-->

<div class="navbar-content">
  <!-- start: SIDEBAR -->
  <div class="main-navigation navbar-collapse collapse">
    <!-- start: MAIN MENU TOGGLER BUTTON -->
    <div class="navigation-toggler">
      <i class="clip-chevron-left"></i>
      <i class="clip-chevron-right"></i>
    </div>
    <!-- end: MAIN MENU TOGGLER BUTTON -->
    <!-- start: MAIN NAVIGATION MENU -->
    <ul class="main-navigation-menu">
      <sec:ifAnyGranted roles="${Role.AvailableRoles.ADMIN.value()}">
        <li class="${'user' == params.controller ? 'active' : ''}">
          <g:link controller="user" action="list">
            <i class="clip clip-user-3"></i>
            <span class="title"><g:message code="users.label.submenu"/></span>
            <span class="selected"></span>
          </g:link>
        </li>
        <li class="${'customValue' == params.controller ? 'active' : ''}">
          <g:link controller="customValue" action="list">
            <i class="clip clip-settings"></i>
            <span class="title"><g:message code="customValue.label"/></span>
            <span class="selected"></span>
          </g:link>
        </li>
      </sec:ifAnyGranted>
      <li class="${'client' == params.controller ? 'active' : ''}">
        <g:link controller="client" action="list">
          <i class="clip clip-users-2"></i>
          <span class="title"><g:message code="clients.label"/></span>
          <span class="selected"></span>
        </g:link>
      </li>
      <li class="${'dataRest' == params.controller ? 'active' : ''}">
        <g:link controller="dataRest" action="tester">
          <i class="clip clip-pencil-2"></i>
          <span class="title"><g:message code="json.tester.label"/></span>
          <span class="selected"></span>
        </g:link>
      </li>
    </ul>
    <!-- end: MAIN NAVIGATION MENU -->
  </div>
  <!-- end: SIDEBAR -->
</div>

grails-app/views/_menu/_topActionButtons.gsp
<div class="page-header">
  <g:link action="list" class="btn btn-purple">
    <i class="fa fa-th-list"></i>
    <g:message code="default.list.label" args="[entityName]"/>
  </g:link>
</div>

grails-app/views/_menu/_user.gsp
<ul class="nav pull-right">
  <li class="dropdown dropdown-btn">
    <%--<sec:ifNotLoggedIn>--%>

    <a class="dropdown-toggle" role="button" data-toggle="dropdown" data-target="#" href="#" tabindex="-1">
      <!-- TODO: integrate Springsource Security etc. and show User's name ... -->
      <i class="icon-user"></i>
      <g:message code="security.signin.label"/><b class="caret"></b>
    </a>

    <ul class="dropdown-menu" role="menu">
      <li class="form-container">
        <form action="login" method="post" accept-charset="UTF-8">
          <input style="margin-bottom: 15px;" type="text" placeholder="Username" id="username" name="username">
          <input style="margin-bottom: 15px;" type="password" placeholder="Password" id="password" name="password">
          <input style="float: left; margin-right: 10px;" type="checkbox" name="remember-me" id="remember-me" value="1">
          <label class="string optional" for="user_remember_me">Remember me</label>
          <input class="btn btn-primary btn-block" type="submit" id="sign-in" value="Sign In">
        </form>
      </li>
      <li class="divider"></li>
      <li class="button-container">
        <!-- NOTE: the renderDialog MUST be placed outside the NavBar (at least for Bootstrap 2.1.1): see bottom of main.gsp -->
        <g:render template="/_common/modals/registerTextLink"/>
      </li>
    </ul>

    <%--</sec:ifNotLoggedIn>--%>
    <%--<sec:ifLoggedIn>--%>

    <%--		<a class="dropdown-toggle" role="button" data-toggle="dropdown" data-target="#" href="#">--%>
    <%--			<!-- TODO: Only show menu items based on permissions (e.g., Guest has no account page) -->--%>
    <%--			<i class="icon-user icon-large icon-white"></i>--%>
    <%--			${user.name}--%>
    <%--			<g:message code="default.user.unknown.label" default="Guest"/> <b class="caret"></b>--%>
    <%--		</a>--%>
    <%--		<ul class="dropdown-menu" role="menu">--%>
    <%--			<!-- TODO: Only show menu items based on permissions -->--%>
    <%--			<li class=""><a href="${createLink(uri: '/')}">--%>
    <%--				<i class="icon-user"></i>--%>
    <%--				<g:message code="user.show.label"/>--%>
    <%--			</a></li>--%>
    <%--			<li class=""><a href="${createLink(uri: '/')}">--%>
    <%--				<i class="icon-cogs"></i>--%>
    <%--				<g:message code="user.settings.change.label"/>--%>
    <%--			</a></li>--%>
    <%--			--%>
    <%--			<li class="divider"></li>--%>
    <%--			<li class=""><a href="${createLink(uri: '/')}">--%>
    <%--				<i class="icon-off"></i>--%>
    <%--				<g:message code="security.signoff.label"/>--%>
    <%--			</a></li>--%>
    <%--		</ul>--%>

    <%--</sec:ifLoggedIn>--%>
  </li>
</ul>

<noscript>
  <ul class="nav pull-right">
    <li class="">
      <g:link controller="user" action="show"><g:message code="default.user.unknown.label"/></g:link>
    </li>
  </ul>
</noscript>