grails-app/domain/co/xtrava/common/CustomValue.groovy
package co.xtrava.common

/**
 * @author: Dmitry Lesnikovich
 */
class CustomValue extends BasePersistentObject {

    String name
    Integer value

    static constraints = {
        name unique: true
        value nullable: true
    }

    enum Name {
        CountDataForHeartRateCalculation(3000),
        CountDataForRespirationCalculation(6000)
        Integer customValue

        Integer value() {
            customValue
        }

        private Name(Integer customValue) {
            this.customValue = customValue
        }
    }
}

grails-app/controllers/co/xtrava/common/CustomValueController.groovy
package co.xtrava.common

import org.springframework.dao.DataIntegrityViolationException

/**
 * CustomValueController
 * A controller class handles incoming web requests and performs actions such as redirects, rendering views and so on.
 */
class CustomValueController {
    def baseSearchService

    static allowedMethods = [save: "POST", update: "POST", delete: "POST"]

    def index() {
        redirect(action: "list", params: params)
    }

    def list() {
        params.max = Math.min(params.max ? params.int('max') : 10, 100)
        def searchParam = params.keyword

        Closure searchRestriction = { builder ->
            if (searchParam) {
                builder.or {
                    
                        builder.ilike("name", "%${searchParam}%")
                    
                }
            }
        }

        def domains = baseSearchService.retrieveListForObject(CustomValue, params, searchRestriction)
        def domainsTotal = baseSearchService.getCountForObject(CustomValue, params, searchRestriction)
        [customValueInstanceList: domains, customValueInstanceTotal: domainsTotal]
    }

    def create() {
        [customValueInstanceInstance: new CustomValue(params)]
    }

    def save() {
        def customValueInstanceInstance = new CustomValue(params)
        if (!customValueInstanceInstance.save(flush: true)) {
            render(view: "create", model: [customValueInstanceInstance: customValueInstanceInstance])
            return
        }

        flash.message = message(code: 'default.created.message', args: [message(code: 'customValue.label', default: 'CustomValue'), customValueInstanceInstance.id])
        redirect(action: "show", id: customValueInstanceInstance.id)
    }

    def show() {
        def customValueInstanceInstance = CustomValue.get(params.id)
        if (!customValueInstanceInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'customValue.label', default: 'CustomValue'), params.id])
            redirect(action: "list")
            return
        }

        [customValueInstanceInstance: customValueInstanceInstance]
    }

    def edit() {
        def customValueInstanceInstance = CustomValue.get(params.id)
        if (!customValueInstanceInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'customValue.label', default: 'CustomValue'), params.id])
            redirect(action: "list")
            return
        }

        [customValueInstanceInstance: customValueInstanceInstance]
    }

    def update() {
        def customValueInstanceInstance = CustomValue.get(params.id)
        if (!customValueInstanceInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'customValue.label', default: 'CustomValue'), params.id])
            redirect(action: "list")
            return
        }

        if (params.version) {
            def version = params.version.toLong()
            if (customValueInstanceInstance.version > version) {
                customValueInstanceInstance.errors.rejectValue("version", "default.optimistic.locking.failure",
                          [message(code: 'customValue.label', default: 'CustomValue')] as Object[],
                          "Another user has updated this CustomValue while you were editing")
                render(view: "edit", model: [customValueInstanceInstance: customValueInstanceInstance])
                return
            }
        }

        customValueInstanceInstance.properties = params

        if (!customValueInstanceInstance.save(flush: true)) {
            render(view: "edit", model: [customValueInstanceInstance: customValueInstanceInstance])
            return
        }

        flash.message = message(code: 'default.updated.message', args: [message(code: 'customValue.label', default: 'CustomValue'), customValueInstanceInstance.id])
        redirect(action: "show", id: customValueInstanceInstance.id)
    }

    def delete() {
        def customValueInstanceInstance = CustomValue.get(params.id)
        if (!customValueInstanceInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'customValue.label', default: 'CustomValue'), params.id])
            redirect(action: "list")
            return
        }

        try {
            customValueInstanceInstance.delete(flush: true)
            flash.message = message(code: 'default.deleted.message', args: [message(code: 'customValue.label', default: 'CustomValue'), params.id])
            redirect(action: "list")
        }
        catch (DataIntegrityViolationException e) {
            flash.message = message(code: 'default.not.deleted.message', args: [message(code: 'customValue.label', default: 'CustomValue'), params.id])
            redirect(action: "show", id: params.id)
        }
    }
}

grails-app/views/customValue/_form.gsp
<%@ page import="co.xtrava.common.CustomValue" %>

<f:field property="name" input-class="form-control"/>

<f:field property="value" input-class="form-control"/>

grails-app/views/customValue/create.gsp
<%@ page import="co.xtrava.common.CustomValue" %>
<!doctype html>
<html>

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="layout" content="dashboard"/>
  <g:set var="entityName" value="${message(code: 'customValue.label', default: 'CustomValue')}"/>
  <title><g:message code="default.create.label" args="[entityName]"/></title>
</head>

<body>
<div class="page-header">
  <g:link action="list" class="btn btn-purple">
    <i class="fa fa-th-list"></i>
    <g:message code="default.list.label" args="[entityName]"/>
  </g:link>
</div>

<div id="create-customValue" class="page-content">
  <g:hasErrors bean="${customValueInstanceInstance}">
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">
        <i class="fa fa-remove"></i>
      </button>
      <g:renderErrors bean="${customValueInstanceInstance}" as="list"/>
    </div>
  </g:hasErrors>

  <g:form action="save" class="form-horizontal" >

  <f:with bean="${customValueInstanceInstance}">
    <g:render template="form"/>
  </f:with>

  <g:render template="/_menu/bottomActionButtons"/>
  </g:form>

</div>

</body>

</html>

grails-app/views/customValue/edit.gsp
<%@ page import="co.xtrava.common.CustomValue" %>
<!doctype html>
<html>

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="layout" content="dashboard"/>
  <g:set var="entityName" value="${message(code: 'customValue.label', default: 'CustomValue')}"/>
  <title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>

<div class="page-header">
  <g:link action="list" class="btn btn-purple">
    <i class="fa fa-th-list"></i>
    <g:message code="default.list.label" args="[entityName]"/>
  </g:link>
</div>

<div id="edit-customValue" class="page-content">
  <g:hasErrors bean="${customValueInstanceInstance}">
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">
        <i class="fa fa-remove"></i>
      </button>
      <g:renderErrors bean="${customValueInstanceInstance}" as="list"/>
    </div>
  </g:hasErrors>

  <g:form method="post" class="form-horizontal" >

  <g:hiddenField name="id" value="${customValueInstanceInstance?.id}"/>
  <g:hiddenField name="version" value="${customValueInstanceInstance?.version}"/>

  <f:with bean="${customValueInstanceInstance}">
    <div class="edit-boundary">
      <g:render template="form"/>
    </div>
  </f:with>

  <g:render template="/_menu/bottomActionButtons"/>
  </g:form>
</div>

</body>

</html>

grails-app/views/customValue/index.gsp
<%@ page import="co.xtrava.common.CustomValue" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'customValue.label', default: 'CustomValue')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-customValue" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-customValue" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="name" title="${message(code: 'customValue.name.label', default: 'Name')}" />
					
						<g:sortableColumn property="value" title="${message(code: 'customValue.value.label', default: 'Value')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${customValueInstanceList}" status="i" var="customValueInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${customValueInstance.id}">${fieldValue(bean: customValueInstance, field: "name")}</g:link></td>
					
						<td>${fieldValue(bean: customValueInstance, field: "value")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${customValueInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/customValue/list.gsp
<%@ page import="co.xtrava.common.CustomValue" %>
<!doctype html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="layout" content="dashboard"/>
  <g:set var="entityName" value="${message(code: 'customValue.label')}"/>
  <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<div class="page-header">
  <g:link action="create" class="btn btn-success">
    <i class="fa fa-plus"></i>
    <g:message code="default.new.label" args="[entityName]"/>
  </g:link>
</div>


<div id="list-customValue" class="page-content">
  <g:if test="${customValueInstanceTotal}">

    <table class="table table-bordered dataTable">
      <thead>
      <tr>
        
        <g:sortableColumn property="name"
                          title="${message(code: 'customValue.name.label', default: 'Name')}"/>
        
        <g:sortableColumn property="value"
                          title="${message(code: 'customValue.value.label', default: 'Value')}"/>
        
      </tr>
      </thead>
      <tbody>
      <g:each in="${customValueInstanceList}" status="i" var="customValueInstance">
        <f:with bean="${customValueInstance}">

          <tr class="${(i % 2) == 0 ? 'odd' : 'even'}">
            
            <td>
              <g:link action="show" id="${customValueInstance.id}">
                <f:display property="name"/>
              </g:link>
            </td>
            
            <td><f:display property="value"/></td>
            
          </tr>
        </f:with>
      </g:each>
      </tbody>
    </table>

    <bs:paginate total="${customValueInstanceTotal}"/>
  </g:if>
  <g:else>
    <g:render template="/_search/noResult" model='[collection: "custom value"]'/>
  </g:else>
</div>

</body>

</html>

grails-app/views/customValue/show.gsp
<%@ page import="co.xtrava.common.CustomValue" %>
<!doctype html>
<html>

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="layout" content="dashboard"/>
  <g:set var="entityName" value="${message(code: 'customValue.label', default: 'CustomValue')}"/>
  <title><g:message code="default.show.label" args="[entityName]"/></title>
</head>

<body>

<div class="page-header">
  <g:link action="list" class="btn btn-purple">
    <i class="fa fa-th-list"></i>
    <g:message code="default.list.label" args="[entityName]"/>
  </g:link>
  <g:link action="edit" id="${customValueInstanceInstance?.id}" class="btn btn-primary">
    <i class="fa fa-pencil"></i>
    <g:message code="default.edit.label" args="[entityName]"/>
  </g:link>
  <g:render template="/_common/modals/deleteTextLink"/>
</div>

    <div id="show-customValue" class="page-content">
      <table class="table table-bordered">
        <tbody>
        
        <tr class="prop">
          <td valign="top" class="name"><g:message code="customValue.name.label"/></td>
          
          <td valign="top" class="value"><f:display bean="${customValueInstanceInstance}" property="name"/></td>
          
        </tr>
        
        <tr class="prop">
          <td valign="top" class="name"><g:message code="customValue.value.label"/></td>
          
          <td valign="top" class="value"><f:display bean="${customValueInstanceInstance}" property="value"/></td>
          
        </tr>
        
        </tbody>
      </table>

    </div>
</body>

</html>